### ISSUE TITLE
Configure GitHub Actions to Run BDD Test Cases

### ISSUE THREAD

**Issue by mwj10** [CSCI-GA-2820-SP23-003/customers#73] opened 2023-03-15 02:30 UTC
**As a** Developer
**I need** provide bdd.yaml workflow file
**So that** tests cases run on every push/pull request to master
   
 ### Details and Assumptions
All test cases has to pass
   
 ### Acceptance Criteria  
If a BDD test fails then changes are rejected 

 ```gherkin
 Given branch been created
 When developer push to remote branch
 Then GitHub action will run every tests cases

 Given branch been created
 When developer issue a pull request
 Then GitHub action will run every tests cases
```

**Comment by ayushjainid** [comment] 2023-03-20 19:16
Duplicate of #61, closing it.

**Closed by ayushjainid** 2023-03-20 19:16 UTC
Labels: technical debt
