### ISSUE TITLE
Configure GitHub Actions to run your unit test cases every time someone pushes to the master branch or submits a Pull Request

### ISSUE THREAD

**Issue by mwj10** [CSCI-GA-2820-SP23-003/customers#68] opened 2023-03-15 02:06 UTC
As a [role]
I need [function]
So that [benefit]

Details and Assumptions

[document what you know]
Acceptance Criteria

Given [some context]
When [action taken]
Then [outcome observed]

**Comment by ayushjainid** [comment] 2023-03-15 04:29
Duplicate of #60

**Closed by ayushjainid** 2023-03-15 04:29 UTC
